name: Release Go Module

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          skipInvalidTags: true

      - name: Create tag
        id: tag
        run: |
          NEW_TAG=${{ steps.semver.outputs.next }}
          echo "Creating new tag: $NEW_TAG"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a $NEW_TAG -m "chore(release): $NEW_TAG"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/UTOL-s/stoken.git
          git push origin $NEW_TAG
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          
          

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: "${{ steps.tag.outputs.new_tag }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Go proxy
        run: |
          go list -m github.com/UTOL-s/stoken@${{ steps.tag.outputs.new_tag }}
